name: Generate SVG and Upload as Artifact

on:
  push:
    branches:
      - main

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのクローン
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 依存関係のインストール
      - name: Install dependencies
        run: npm install axios

      # SVGの生成
      - name: Generate SVG
        run: node generate-piechart.js

      # アーティファクトのアップロード
      - name: Upload SVG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: piechart-svg
          path: output.svg

  create-release:
    runs-on: ubuntu-latest

    needs: generate-svg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SVG artifact
        uses: actions/download-artifact@v4
        with:
          name: piechart-svg

      - name: Create release
        shell: bash
        run: |
          ls
          wget -c https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz
          tar xfv ghr_v0.17.0_linux_amd64.tar.gz
          ghr_v0.17.0_linux_amd64/ghr -u nishinji -r pie_chart -recreate -n 'Automatic CI builds' continuous output.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    